### PR TITLE
Newsweek layout design

### PR DESCRIPTION
**Pull request by Gabkings**
# Project Name
## Newsweek

Screenshot at 2020-09-09 01-26-44

Building a page using HTML, CSS, and Bootstrap that matches the appearance of this page [Newsweek](https://www.newsweek.com/)

Additional description of the project and its features.

- The HTML mark up a layout using the required tags for headers, main and footer

- Adding styling to HTML sections in the index page

- Identifying browser breaking points for responsive 

- Using media queries for designing the breaking points styles for different devices

## Built With

- HTML
- CSS

## Getting Started
1. Clone the project via this link: [Project](https://github.com/Gabkings/NewsWeek.git)
2 `cd NewsWeek`
3 Open the index.html file in your favorite browser

### Prerequisites
HTML5 and CSS

### Setup
1. Clone the project via this link: [Project](https://github.com/Gabkings/NewsWeek.git)
2 `cd NewsWeek`
3 Open the index.html file in your favorite browser
4 Make some changes to the project

## Authors

👤 **Author1**

- GitHub: [@githubhandle](https://github.com/Gabkings)
- LinkedIn: [LinkedIn](https://www.linkedin.com/in/gabriel-gitonga-b5a611183/)

## 🤝 Contributing

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](issues/).

## Show your support

Give a ⭐️ if you like this project!

## Acknowledgments

- Microverse
- W3schools
- Freecodecamp
- Developer.mozilla
- Learnshayhowe
- Odin project
- Bootstrap

## 📝 License

This project is [MIT](lic.url) licensed.

### CODE REVIEW

**Comment by kevcap** [comment]
# [STATUS] INVALID PULL REQUEST 🛑

### Sorry team, TSE's can't review invalid pull requests, please, to get your project approved, you guys have to take a step back and do the following:
 - [ ] Your readme file is empty, please implement it with microverse's template or with that content that you added at the description of the pull request.

**Please make the required changes and resubmit for a new code review once you are ready**

## As always, I wish you all the very best and see you at the top🚀

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)


<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Comment by kevcap** [comment]
# [STATUS] INVALID PULL REQUEST 🛑

### Sorry team, TSE's can't review invalid pull requests, please, to get your project approved, you guys have to take a step back and do the following:
 - [ ] Your readme file is still empty, please implement it with microverse's template or with that content that you added at the description of the pull request.

**Please make the required changes and resubmit for a new code review once you are ready**

## As always, I wish you all the very best and see you at the top🚀

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)


<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Comment by Gabkings** [comment]
Aright I have made the changes you have requested

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

#### Hey @Gabkings,  your project is looking really good, however, to accomplish as the actual page, you required to do these changes, listed below:
 
_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, to get more knowledge and have a better project to add at your portfolio.
 
 
## [REQUIRED CHANGES]
#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
- [ ] Remove all those borders (They're in small, medium and large screens)
image
- [ ] There are some overlapping in your project (in small, medium and large screens), please remove all the overlapping such as those on the image below ⤵ 
image
- [ ] Here should be an embedded logo, not a text, fix that
image
- [ ] In small and medium screens, you should remove that section, since it doesn't appear at the original one in medium or small screens⤵
image
- [ ] That "Cover" text should be in front of the image, not below it.
- [ ] Your project has horizontal overflow in MEDIUM and SMALL screens, and it's causing a horizontal bar, kindly remove it.
image
- [ ] That button shouldn't be overlapping, it should be inside that NEWSLETTER box, fix that.
image
- [ ] In small screens your The Debate section and the section below that are with broken layout (both are shrinked). Please fix that ⤵
image
image
- [ ] In small screens your page don't have that border left and right, and is also overlapping in some elements such as the element below⤵
image

### Summing up all the above ⬆ requirements ⤵:
- [ ] Remove ALL unnecessary borders (in small, medium, and large screens)
- [ ] Remove ALL the overlapping in your project (in small, medium, and large screens)
- [ ] Remove ALL the overflow (in small, medium, and large screens)
- [ ] Remove that horizontal bar (in small and medium screens)
- [ ] Fix that shrinked sections in small screens
- [ ] Implement the left and right margin in small screens

#### Good practices REQUIREMENTS (Those changes to make you code like a pro 👽)⤵
- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
image
Your HTML will be something like this: 
image
Apply the same logic above in **ALL** those repeated rules listed below:
image

- [ ] Check usage of [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp)  (e.g. ) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/semantic_html_requirement.png) from Pathwright)
Explanation: Your page have 0 `<article>` and `<section>` tags, but it definitively should have a lot of them.


## Summary
✨ The project looks nice, just have to fix some layout issues 💯
✨ Nice usage of the bootstrap!
Just have to implement that minor changes listed above, and I know that It will be easy for you! 🔧



## [OPTIONAL CHANGES]
 - [ ] Remove that "Hello world" at the title and add the title proper of the page (Newsweek - News, Analysis, Politics, Business, Technology)

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Nice work so far. 👍 

- Good job implementing most of the changes requested by the previous TSE.

## However, there are some changes required 👀 🧰 🔨 🔧 

- The biggest issue still affecting your project is unwanted horizontal scroll:

image

Pay attention to all screen sizes: they all present this unnecessary horizontal space which causes the page to scroll. It's a small bug, but very important, and surely it has a solution.

- As @kevincappuccino mentioned previously, it would be nice to keep your code DRY by assigning an individual CSS class to your most-frequently used attributes. In the case of your CSS, the attributes you seem to be using most often are:
```
     font-size: 15px; // 4 times
     font-size: 16px; // 4 times
     border: none; // 6 times
     font-size: 24px; // 6 times
     color: #f72210; // 12 times
     font-weight: bold; // 16 times
     color: black; // 21 times
     text-decoration: none; // 23 times
```
For example, instead of using `text-decoration: none` 23 times in your CSS, you could define a single class, `.no_decoration { text-decoration: none; }`, and use that in your `HTML` with `class="no_decoration..."`.

Besides that, your project seems pretty complete. Fix these issues and re-submit to see if the next TSE finds some more things to improve!

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
## Status: Changes requested :red_circle: 

### Hello @Gabkings :wave: 

### Thank you for fixing the horizontal scroll issue, but we still have one more thing to fix:

- [ ] You still have a lot of repeating CSS properties, please create classes for these in order to improve your code:

      23 |   text-decoration: none;
      19 |   }
      19 |   color: black;
      14 |   font-weight: bold;
      12 |   color: #f72210;
       6 |   font-size: 24px;

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

#### Hey @Gabkings,  your project is looking really good, however, to accomplish as the actual page, you required to do these changes, listed below:

## [REQUIRED CHANGES]
As @MuriloRoque requested, you still have to implement the following ⤵
- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
image
Your HTML will be something like this: 
image
Apply the same logic above in **ALL** those repeated rules listed below:
```
      19 |   color: black;
      14 |   font-weight: bold;
      12 |   color: #f72210;
       6 |   font-size: 24px;

```

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

#### Hey @Gabkings, well done implementing some of my requested changes, your project is looking really good, however, it seems that you still have a lot of repeated rules, so is required to do these changes, listed below:

## [REQUIRED CHANGES]
- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
image
Your HTML will be something like this: 
image
Apply the same logic above in **ALL** those repeated rules listed below:
```
      16 |   font-weight: bold;
      13 |   color: black;
      13 |   text-decoration: none;
       6 |   border: none;
       6 |   font-size: 24px;
```

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

#### Hey @Gabkings, well done implementing some of my requested changes, your project is looking really good, however, it seems that you still have a lot of repeated rules, so is required to do these changes, listed below:

## [REQUIRED CHANGES]
- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
image
Your HTML will be something like this: 
image
Apply the same logic above in **ALL** those repeated rules listed below:
```
     16 |   font-weight: bold;
     13 |   color: black;
       9 |   text-decoration: none;
       6 |   border: none;
       6 |   font-size: 24px;
```

## Please, to get your project approved, implement the required changes. 🔧

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

#### Hey @Gabkings, well done implementing some of my requested changes, your project is looking really good, however, it seems that you still have a lot of repeated rules, so is required to do these changes, listed below:

## [REQUIRED CHANGES]
If you break your code while implementing the required changes, Is possible that TSE points it out. And that happened in this case ⤵.
- [ ] Looks like you have broken your navbar in small and medium screens, please fix them.
#### Small
image
#### Medium
image

# ⚠ Mr @Gabkings please note that this is the 7th time that a TSE ask you to do this change, you're capable to do it!! I believe In your potential, so kindly implement it ⤵

- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
image
Your HTML will be something like this: 
image
Apply the same logic above in **ALL** those repeated rules listed below:
image

### 😕 Unfortunately you still have a lot of repeated rules (add variables without removing the repeated rules is not DRY code, kindly note that DRY code means Don't Repeat Yourself)

### Please use my example above or follow @voscarmv example, but implement your classes and remove that repeated css rules.

## Please, to get your project approved, implement the required changes. 🔧

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Review by BrittanyBlake — APPROVED** [review]
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****

_P.S. You have not added a live demo link in your readme. Please create one using [githack](raw.githack.vom)or gh-pages. 😄_ 

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

**Pull request merged**
